include: package:effective_dart/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    avoid_function_literals_in_foreach_calls: false
    avoid_relative_lib_imports: true
