name: peacock_and_quill
description: PeacockAndQuill is a cross platform application used to present information using a classic PowerPoint style while allowing your audience to participate.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1 # controlled by Git tags and CodeMagic build number

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.5 #used for firestore mobile
  dio: ^4.0.4 # used for http
  firebase: ^9.0.2 # used for firestore and storage on web
  firebase_core: ^1.10.6 # enables using multiple firebase projects
  firebase_auth: ^3.3.4 # used for user login
  firebase_storage: ^10.2.4 # used to bring in images for presentation
  flutter_svg: ^1.0.0 # used to support svg in mobile
  google_sign_in: ^5.2.1 # used to sign in with google
  provider: ^6.0.2 # used for dependency injection
  responsive_builder: ^0.4.1 # used to separate device size specific views
  rxdart: ^0.27.3 # used for advanced streams
  universal_html: ^2.0.8 # used to allow cross platform development
  photo_view: ^0.13.0 # zoomable images
  sign_in_with_apple: ^3.3.0 # sign in with apple
  device_info: ^2.0.3 # used to detect what version of apple we're on

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.0.0
  flutter_launcher_icons: ^0.9.2 # create launcher icons

flutter_icons:
  image_path_android: 'assets/icon/ios-and-google-icon.png'
  image_path_ios: 'assets/icon/ios-and-google-icon.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: 'assets/icon/google-play-icon-background.png' # only available for Android 8.0 devices and above
  adaptive_icon_foreground: 'assets/icon/google-play-icon-foreground.png' # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ # include everything in the assets folder

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-BlackItalic.ttf
  #         weight: 800
  #         style: italic
  #       - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Montserrat-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
